Add Home, Login and SignIn pages
ya-praktikum-hornets/ya-praktikum-arkanoid pull request #19
Opened 2022-02-18 14:59 UTC by Evgood

Добавил следующие страницы:
- Home
- Login
- SignIn

Добавил themeProvider.

Есть сложности с типами пропсов, буду благодарен, если подскажите. 
По styled components - первый опыт. Надеюсь верно понял принцип модульности. Если нет, поправьте.

2022-02-20 10:15 UTC, Barnicle requested changes
Оставил свои комментарии, хорошо поработал!
Алиасы можно добавить или в этой задаче или можем создать отдельную таску для этого.

2022-02-20 10:15 UTC, Barnicle commented on src/components/Forms/SignInForm/style.ts
> +        margin-top: 24px;
margin-top нежелательно использовать, насколько сложно будет избавиться от него тут?

2022-02-20 10:26 UTC, Evgood commented on src/components/Forms/LoginForm/style.ts
> +import pattern from '../../../../public/images/pattern.svg'
С Алисами согласен. Можно тут добавить, чтобы не заводить новую таску

2022-02-20 10:35 UTC, Evgood commented on src/components/Forms/SignInForm/style.ts
> +const FormPattern = styled.div`
Вот тут вопрос к знатокам) С одной стороны иметь общие стили и переиспользовать их удобно, DRY и т.д. А с другой вроде как сам компонентный подход говорит о том, что стили должны быть изолированными, чтобы они не зависели от глобальных и не наследовались.

2022-02-20 10:38 UTC, Evgood commented on src/components/Button/style.ts
> +const ButtonElement = styled.button<{ primary: boolean }>`
Гляну 👌

2022-02-20 10:39 UTC, Evgood commented on src/components/Forms/LoginForm/LoginForm.tsx
> +import { FormLayout, FormPattern, FormWrap } from './style';
Давайте так, подправлю

2022-02-20 10:40 UTC, Evgood commented on src/components/Forms/SignInForm/style.ts
> +        margin-top: 24px;
> margin-top нежелательно использовать, насколько сложно будет избавиться от него тут?

Что-то придумать можно, думаю.

А подскажи в чем проблема margin тут?

2022-02-20 10:48 UTC, Evgood commented on webpack.config.js
> +            loader: 'image-webpack-loader',
> Что делает этот лоудер?

Добавил для загрузки изображений. Лоудер работает с связке с file-loader, поэтому его тоже добавил, и умеет минифицировать изображения с imagemin.

В целом сейчас он используется просто как загрузчик картинок и сжатие не используется. Если он излишен, давайте заменим.

2022-02-20 11:08 UTC, kotosha-real reviewed
Хорошая работа)
В целом даже хорошо, что тут и компоненты, и страницы, на них сделанные, потому что можно обсудить сразу всё и так же быстро всё поправить. Но как говорили в чате — да, давай лучше в следующий раз таски дробить сильнее

2022-02-20 11:08 UTC, kotosha-real commented on src/styles/theme.ts
> +    colors: {
🧐
Раз уже есть зачатки темизации, то предлагаю это всё задавать через `css`-вары. Потом будет легко и просто переключить тему через глобальный класс с установленными для него переменными. Также, обычно темы двухуровневые: есть палетка с цветами и есть тема, которая палетку использует, например
```
// Палетка, тут переменные называются "в лоб"
--black: #000;

// Тема, тут переменные названы семантично
--font-color: var(--black);
```

2022-02-20 11:11 UTC, kotosha-real commented on src/components/Forms/SignInForm/style.ts
> +const FormPattern = styled.div`
Тут ситуация другая ведь)
У тебя по сути заново созданы компоненты, которые ты уже создал для такого же кейса в другом месте. Это как если бы ты тут снова кнопку создал. Так что противоречий нет, это всё ещё компонентый подход, к тому же компоненты станут переиспользуемыми)

2022-02-20 11:30 UTC, Barnicle commented on src/components/Forms/LoginForm/LoginForm.tsx
> +                <span>Нет аккаунта?</span>
Почему лучше в json хранить? Мне казалось такой подход необходим только когда в проекте несколько языков.

2022-02-20 11:35 UTC, Barnicle commented on src/components/Forms/SignInForm/style.ts
> +        font-size: 24px;
Согласен, можно в глобально задать дефолтный font-size: 10, чтобы rem был было легче считывать 1rem = 10px/ 1.5rem = 15px и т.д.

2022-02-20 11:47 UTC, Barnicle commented on src/components/Forms/SignInForm/style.ts
> +        margin-top: 24px;
> > margin-top нежелательно использовать, насколько сложно будет избавиться от него тут?
> 
> 
> 
> Что-то придумать можно, думаю.
> 
> 
> 
> А подскажи в чем проблема margin тут?

[Вот](https://habr.com/en/post/340420/), как мне кажется, неплохая статья на эту тему. Если кратко, то отступа должен идти от первого элемента к второму. Часто необходимость margin-top можно заменить на padding у родительского блока. У всего этого, конечно, есть исключения, поэтому вопрос дискуссионный))

2022-02-20 12:30 UTC, Evgood commented on src/components/Forms/LoginForm/LoginForm.tsx
> +const LoginForm = (props) => {
Вот с этим и был вопрос. 

Я правильно понимаю, что для каждого компонента нужно отдельно типизировать пропсы, то есть описать какие поля и какого типа они принимают?

И где хранить их? В общей папке с типами или в файле с компонентом или в папке с компонентом отдельным файлом?

2022-02-20 12:30 UTC, Evgood commented on src/components/Forms/LoginForm/LoginForm.tsx
> +const LoginForm = (props) => {
> ❗
> Пропсы в компонентах нужно типизировать

Вот с этим и был вопрос.

Я правильно понимаю, что для каждого компонента нужно отдельно типизировать пропсы, то есть описать какие поля и какого типа они принимают?

И где хранить их? В общей папке с типами или в файле с компонентом или в папке с компонентом отдельным файлом?

2022-02-20 12:39 UTC, kotosha-real commented on src/components/Forms/LoginForm/LoginForm.tsx
> +                <span>Нет аккаунта?</span>
Даже если язык один, тексты - это контент. Чтобы поменять контент, не нужно менять код. Если вдруг нужно, то что-то явно не так)

2022-02-20 12:41 UTC, kotosha-real commented on src/components/Forms/LoginForm/LoginForm.tsx
> +const LoginForm = (props) => {
Можно хоть в файле с компонентом. Мы описываем их в формате `export interface ComponentNameProps` прямо в этом же файле. Экспортируем, потому что интерфейс может понадобиться в каком-то другом месте

2022-02-20 12:42 UTC, kotosha-real commented on src/components/Forms/LoginForm/LoginForm.tsx
> +const LoginForm = (props) => {
Хранить в общей папке компонентов точно не надо. Всё, что относится к компоненту/модулю, лежит рядом с ним. Это и понятно, и ожидаемо, и не провоцирует появление глобальной помойки типов

2022-02-20 12:45 UTC, kotosha-real commented on src/components/Forms/SignInForm/style.ts
> +        font-size: 24px;
Лучше в процентах, чтобы пользовательские настройки не сбивать. Обычно пишут 62,5%, потому что это очень часто и есть 10пх (дефолтный шрифт обычно 16рх, 16 * 0,625 = 10пх)

2022-02-20 18:17 UTC, Evgood commented
> Хорошая работа)
> В целом даже хорошо, что тут и компоненты, и страницы, на них сделанные, потому что можно обсудить сразу всё и так же быстро всё поправить. Но как говорили в чате — да, давай лучше в следующий раз таски дробить сильнее

Спасибо за ревью.

По таскан понял, буду дробить.

По комментариям внес правки. Вроде ничего не пропустил.

2022-02-20 18:18 UTC, Evgood commented
> Оставил свои комментарии, хорошо поработал!
> Алиасы можно добавить или в этой задаче или можем создать отдельную таску для этого.

Спасибо за ревью.

Алиасы добавил в этой таске

2022-02-20 18:24 UTC, Evgood commented on src/components/Forms/SignInForm/SignInForm.tsx
> +                <span>Есть аккаунт?</span>
Тут должна быть ссылка, но не стал добавлять пока, потому что подумал все равно потом менять на линки от роутера.

2022-02-20 18:26 UTC, Evgood commented on src/components/Forms/SignInForm/style.ts
> +        font-size: 24px;
> Лучше в процентах, чтобы пользовательские настройки не сбивать. Обычно пишут 62,5%, потому что это очень часто и есть 10пх (дефолтный шрифт обычно 16рх, 16 * 0,625 = 10пх)

Сделал в итоге в `rem` и с `font-size: 10px`. С процентами чего-то не завелось или что-то не так сделал.

2022-02-20 18:26 UTC, Evgood commented on src/components/Forms/SignInForm/style.ts
> +        font-size: 24px;
> Лучше в процентах, чтобы пользовательские настройки не сбивать. Обычно пишут 62,5%, потому что это очень часто и есть 10пх (дефолтный шрифт обычно 16рх, 16 * 0,625 = 10пх)

Сделал в итоге в `rem` и с `font-size: 10px`. С процентами чего-то не завелось или что-то не так сделал.

2022-02-20 18:35 UTC, Evgood commented on src/components/Button/Button.tsx
> +const Button = (props) => {
Получается что так) Это все следствие первого знакомства со styled components.

2022-02-20 18:53 UTC, Barnicle approved these changes

2022-02-20 18:53 UTC, Barnicle commented on src/components/Inputs/Inputs.tsx
> +        <StyledInput {...props} type='password' />
Кажется тут и ниже забыл изменить тип

2022-02-20 18:53 UTC, Barnicle commented on webpack.config.js
> +    alias: {
Есть такой [плагин для webpack](https://www.npmjs.com/package/tsconfig-paths-webpack-plugin) c его помощью можно не дублировать алиасы - webpack будет брать за основу те, чтобы прописаны в нашем tsconfig

2022-02-20 18:56 UTC, Evgood commented on src/components/Inputs/Inputs.tsx
> +        <StyledInput {...props} type='password' />
Точно, сейчас исправлю

2022-02-20 19:17 UTC, Evgood commented on webpack.config.js
> +    alias: {
Спасибо, не знал про плагин

2022-02-21 21:01 UTC, kotosha-real commented on src/styles/theme.ts
> +        white: '#ffffff',
❗
Кажется, что их можно объединить. И, как уже писал, если какие-то цвета именуешь семантически, то нужно везде этого придерживаться, поэтому `white` тут лишний
```suggestion
        // Colors
        primary: '#0B82FF',
        secondary: '#272C32',
        success: '#30BF90',
        danger: '#FF5730',
        line: '#E8E8E8',
        white: '#ffffff',
```

2022-02-26 14:35 UTC, kotosha-real approved these changes
🕵🏻‍♂️
Есть аппрув!
Но также есть пара комментов, вернись к ним, плиз, после этого можно мержить без повторного ревью

2022-02-26 14:35 UTC, kotosha-real commented on src/components/Header/Header.tsx
> +    type?: 'link' | 'button',
🧐
Это тоже хорошо бы в енам

2022-02-26 14:35 UTC, kotosha-real commented on src/components/Forms/Form/styled.ts
> +    max-height: 65rem;
Вот тут коммент не избегай)

2022-02-28 09:46 UTC, merged